CREATE TABLE IF NOT EXISTS request_checksheet (
    id INT PRIMARY KEY AUTO_INCREMENT,
    request_number VARCHAR(50) UNIQUE NOT NULL,
    checksheet_id INT NOT NULL,
    qty INT NOT NULL,
    status ENUM('pending','approved','rejected','completed') DEFAULT 'pending',
    requested_by INT NOT NULL,
    approved_by INT NULL,
    approved_at TIMESTAMP NULL,
    notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (checksheet_id) REFERENCES master_checksheet(id) ON DELETE RESTRICT,
    FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_request_number (request_number),
    INDEX idx_status (status),
    INDEX idx_requested_by (requested_by),
    INDEX idx_checksheet_id (checksheet_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
